[package]
name = "stake-contract"
version = "0.1.0"
authors = ["Jules de Smit <julesdesmit@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
canonical = {version = "0.5", default-features = false}
canonical_derive = "0.5"
canonical_host = { version = "0.5", optional = true }
rusk-abi = { path = "../../rusk-abi", version = "0.1" }
dusk-bls12_381 = { version = "0.6", default-features = false, features = ["canon"] }
dusk-bls12_381-sign = { git = "https://github.com/dusk-network/bls12_381-sign", branch = "main", default-features = false, features = ["canon"] }
dusk-kelvin-map = "0.3"
phoenix-core = {git="https://github.com/dusk-network/phoenix-core", tag="v0.9.1", features = ["canon"]}

[features]
host = ["canonical_host"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
